### ISSUE TITLE
Things to do

### ISSUE THREAD

**Issue by parker57** [jamesevickery/astonhack2017#1]
- James, Johnny wanted the output from the script named nlp to display
- Could have main slide be the CVC :+1: :^) score, name and value of the highest rated Majestic topic, community metric :thinking:, and a aggregate grade (A-F?) :grapes: each occupying a quarter :question: 
- Slide to the right, a bit more in-depth use of majestic API, slide to the left elaborates on other values returned from nlp.
- Collection of imperfect metrics, rounded approach

:grapes: No idea how we are going to have an aggregate. Just take an avg of the Majestic metrics and the CVC? Ugly but might present well.

P.S :grapes: = *

:crab:

**Comment by jmsv** [comment]
All done
