### ISSUE TITLE
Voting

### ISSUE THREAD

**Issue by j-m** [jamesevickery/astonhack2017#3]
Voting currently results in an error not investigated it much because (if possible) I'd like you to return the new percentage so the user doesn't have to refresh

**Comment by jmsv** [comment]
Isn't the refreshing bug thing a front-end problem? The votes are updated live so you need to just redo the GET request from the extension. Maybe a refresh button?

**Comment by j-m** [comment]
Yeah it is, I considered that but would it not make more sense to only refresh the user votes? Seems like a waste of resources to have to recalculate allll the values given only the vote score will have changed.

**Comment by jmsv** [comment]
Oh so you want the `vote-stats` endpoint back? I'll do that now
