### ISSUE TITLE
"Hmmm looks like something went wrong :'(" on all working vote requests

### ISSUE THREAD

**Issue by jmsv** [jamesevickery/astonhack2017#4]
When 'yes' or 'no' is clicked on the 'People's vote' section, the server accepts and stores the vote and returns a `200`, but "Hmmm looks like something went wrong :'(" is displayed on a red banner

**Comment by j-m** [comment]
http://faktnews.org:5000/v4?search=www.bbc.co.uk/news/world-us-canada-41958553

Internal Server Error - so backend
I can't test voting until that's resolved

**Comment by jmsv** [comment]
Hmm, voting was working when I tested, not sure what's happened to `/v4` though, I'll have a look

**Comment by j-m** [comment]
Seems to be working now (/v4 that is)
The reason it fails is because 'OK' isn't in JSON

**Comment by jmsv** [comment]
The extension seems to be making dodgy vote calls; it just got this request:
`/vote/v1?url=https://github.com/jamesevickery/astonhack2017/issues/4`.
There's no `trusted` URL param.

**Comment by jmsv** [comment]
Have a look at the above commit, 832b619...

`/vote-stats?url=https://jamesvickery.net/` now returns:

```json
{
    "VoteStat": 89
}
```

and `/vote/v1?url=https://jamesvickery.net/&trusted=y` returns:

```json
{
    "Status": "OK"
}
```

_All JSON everythang_ :100:

**Comment by jmsv** [comment]
Think that fixed it (reopen if not)

**Comment by j-m** [comment]
Is it possible to combine them so` /vote/v1?url=https://jamesvickery.net/&trusted=y` returns `{"VoteStat":89}`?

**Comment by jmsv** [comment]
@jauntum Opened #5
