### ISSUE TITLE
Return new VoteStat from vote endpoint

### ISSUE THREAD

**Issue by jmsv** [jamesevickery/astonhack2017#5]
`vote` endpoint should return `VoteStat`

**Comment by j-m** [comment]
Pushed the front-end preemptively

**Comment by jmsv** [comment]
Done, however you might want to revisit your push as the new stuff is in `/vote/v2`

**Comment by jmsv** [comment]
Example: `faktnews.org:5000/vote/v2?url=https://jamesvickery.net/&trusted=y` returns

```json
{
    "Status": "OK",
    "VoteStat": 89
}
```

**Comment by jmsv** [comment]
Issue requirements are done so closing this, although feel free to refer to it in related commits (put "#5" in commit message)
