### ISSUE TITLE
Encoding? issue

### ISSUE THREAD

**Issue by j-m** [jamesevickery/astonhack2017#6]
http://www.faktnews.org:5000/vote/v2?url=https://github.com/jamesevickery/astonhack2017/issues/5#issuecomment-344078058&trusted=y

Returns an error, does it think the `&trusted=y` is for the provided URL perhaps?
I'll leave both ends of encoding to you

**Comment by jmsv** [comment]
Yeah I've been meaning to fix this, I'll do it soonish
