### ISSUE TITLE
Grammar Analysis doesn't change

### ISSUE THREAD

**Issue by j-m** [jamesevickery/astonhack2017#7]
Not sure if it's supposed to be like this, my interpretation was that it was different for every website?
Possible backend problem?

**Comment by jmsv** [comment]
I'm just getting values from Charlie's code. @parker57 could you have a look?

**Comment by parker57** [comment]
OK I will fix it, It's probably something stupid.
I'm testing it on this bespoke site https://parker57.github.io/nouns.html :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :dog: :wink:

**Comment by parker57** [comment]
It was hard-coded to look at the BBC chat-bot site instead or the url argument.

**Comment by jmsv** [comment]
Very untrustworthy website 

---
![Bad website](https://user-images.githubusercontent.com/14852491/32779288-0dc575e8-c935-11e7-8801-db3c40466e18.png)

**Comment by j-m** [comment]
Charlie just showed me that nlp.py does return different values depending on the site, is your server up to date James?
